"""Changed the associative table to full model based

Revision ID: 5bee2c337188
Revises: 0f6669222f5e
Create Date: 2022-05-28 12:44:18.537110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bee2c337188'
down_revision = '0f6669222f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_shows', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('all_shows', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'all_shows', 'artists', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'all_shows', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'all_shows', type_='foreignkey')
    op.drop_constraint(None, 'all_shows', type_='foreignkey')
    op.drop_column('all_shows', 'venue_id')
    op.drop_column('all_shows', 'artist_id')
    # ### end Alembic commands ###
