"""Modified models artist and venues genre datatype to arrays

Revision ID: ac05044cd0c3
Revises: 5bee2c337188
Create Date: 2022-05-29 19:29:32.672950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac05044cd0c3'
down_revision = '5bee2c337188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'genres',
               type_=sa.ARRAY(sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'genres',
               existing_type=sa.ARRAY(sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
